source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4'
pod 'pop', '~> 1.0'
pod 'SVWebViewController', '~> 0.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ADLivelyCollectionView'